import {
  IoSearch,
  IoClose,
  IoWarning,
  IoMoonOutline,
  IoCloseSharp,
  IoReload,
} from "react-icons/io5";
import { TbLetterV, TbLoader2 } from "react-icons/tb";
import { AiFillDashboard } from "react-icons/ai";
import { ImDisplay } from "react-icons/im";
import { RiBankFill } from "react-icons/ri";

import {
  FaSync,
  FaExchangeAlt,
  FaTrash,
  FaInfoCircle,
  FaFileDownload,
  FaAddressCard,
  FaEnvelopeOpenText,
  FaEye,
  FaKey,
  FaPowerOff,
  FaHeartbeat,
  FaTimes,
  FaHdd,
  FaShareAlt,
  FaUsb,
  FaObjectGroup,
  FaObjectUngroup,
  FaTh,
  FaCheckDouble,
  FaPlus,
  FaLandmark,
  FaBook,
  FaCheck,
  FaLockOpen,
  FaUser,
  FaUsersCog,
  FaFilter,
  FaDownload,
  FaBuilding,
  FaBell,
  FaDesktop,
  FaBiohazard,
  FaLightbulb,
  FaShieldAlt,
  FaSitemap,
  FaGlobeEurope,
  FaFlask,
  FaSkull,
  FaBox,
  FaHistory,
  FaArchive,
  FaChevronDown,
  FaSatelliteDish,
  FaMagic,
  FaLevelUpAlt,
  FaCalendarDay,
  FaDatabase,
  FaList,
  FaFile,
  FaCogs,
} from "react-icons/fa";

import { FaFolderOpen } from "react-icons/fa6";

import { MdInsertChart, MdViewList, MdOutlineInventory } from "react-icons/md";
import { ImLab } from "react-icons/im";
import { TiGroup } from "react-icons/ti";
import { LuArrowLeftRight, LuLogIn } from "react-icons/lu";
import { IoIosArrowDown, IoMdSettings, IoMdApps } from "react-icons/io";
import { LiaBookSolid } from "react-icons/lia";
import { RiLogoutBoxRLine } from "react-icons/ri";
import { GiNuclear } from "react-icons/gi";
import { PiBankFill } from "react-icons/pi";
import { FiSun, FiRefreshCcw } from "react-icons/fi";
import { GrMenu } from "react-icons/gr";

export {
  FaSync,
  FaExchangeAlt,
  FaTrash,
  FaInfoCircle,
  FaFileDownload,
  FaAddressCard,
  FaEnvelopeOpenText,
  FaEye,
  FaKey,
  FaHeartbeat,
  FaTimes,
  FaHdd,
  FaShareAlt,
  FaUsb,
  TbLoader2,
  FaObjectGroup,
  FaObjectUngroup,
  FaTh,
  FaCheckDouble,
  FaPlus,
  FaUsersCog,
  FaCogs,
  FaLandmark,
  TbLetterV,
  IoReload,
  FaFolderOpen,
  FiRefreshCcw,
  IoCloseSharp,
  FaBook,
  MdOutlineInventory,
  IoMdApps,
  GrMenu,
  IoMoonOutline,
  FiSun,
  IoMdSettings,
  FaFile,
  FaList,
  FaCalendarDay,
  FaDatabase,
  FaLevelUpAlt,
  FaMagic,
  FaSatelliteDish,
  FaChevronDown,
  FaCheck,
  IoWarning,
  IoClose,
  FaSitemap,
  FaGlobeEurope,
  FaFlask,
  FaSkull,
  FaBox,
  FaPowerOff,
  FaHistory,
  FaArchive,
  FaShieldAlt,
  PiBankFill,
  GiNuclear,
  FaLightbulb,
  FaBiohazard,
  FaDesktop,
  FaBell,
  RiLogoutBoxRLine,
  LiaBookSolid,
  FaBuilding,
  LuLogIn,
  IoIosArrowDown,
  FaFilter,
  FaDownload,
  LuArrowLeftRight,
  MdViewList,
  TiGroup,
  ImLab,
  IoSearch,
  AiFillDashboard,
  ImDisplay,
  RiBankFill,
  FaLockOpen,
  FaUser,
  MdInsertChart,
};
